[package]
name = "unreal-xtrainer"
version = "0.1.0"
authors = ["Jamar Vales"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.19.0"
bindings = { path = "bindings" }
